// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lrgexuudpodmvqyhpqzd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxyZ2V4dXVkcG9kbXZxeWhwcXpkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI4NTk5MjUsImV4cCI6MjA2ODQzNTkyNX0.GKKe-M12WQfSGWo96M0J1t7QXueGEy4AsmohYbBQUyg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});